# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - cmd: |
          VCPKG_BIN="$(which vcpkg)"
          VCPKG_ROOT="$(dirname "$VCPKG_BIN")/../apps/vcpkg/current"
          if ! cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"; then
            rm -rf build
            cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE="$VCPKG_ROOT/scripts/buildsystems/vcpkg.cmake"
          fi
      - cmd: |
          cmake --build build    
